version: '3.3'

volumes:
  pg_data:
  static:
  media:
  data:
  docs:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: basmelek/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/media
      - data:/data
      - docs:/usr/share/nginx/html/api/docs
  frontend:
    image: basmelek/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: basmelek/foodgram_gateway
    ports:
      - 9000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
    depends_on:
    - backend
    - frontend