# Generated by Django 3.2.23 on 2024-01-18 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='recipes.recipes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='users.foodgramuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.CharField(default=0, max_length=200, verbose_name='Размерность массы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredients',
            name='name',
            field=models.CharField(default=0, max_length=200, verbose_name='Название ингридиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='users.foodgramuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='recipes/images/'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.ingredients'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='name',
            field=models.CharField(default=0, max_length=200, verbose_name='Название тэга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='text',
            field=models.CharField(default=0, max_length=200, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='followed_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.foodgramuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='subscriber',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.foodgramuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='color',
            field=models.CharField(default=0, max_length=200, verbose_name='Название тэга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='name',
            field=models.CharField(default=0, max_length=200, verbose_name='Название тэга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.CharField(default=0, max_length=200, verbose_name='Название тэга'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TagsRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_recipes', to='recipes.recipes')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_recipes', to='recipes.tags')),
            ],
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(through='recipes.TagsRecipes', to='recipes.Tags'),
        ),
    ]
