# Generated by Django 3.2.23 on 2024-01-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20240122_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagsrecipes',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='tagsrecipes',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='ingredientsinrecipes',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients'),
        ),
        migrations.AlterField(
            model_name='ingredientsinrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.IngredientsInRecipes', to='recipes.Ingredients'),
        ),
    ]
