# Generated by Django 3.2.23 on 2024-01-24 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20240124_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsinrecipes',
            options={'default_related_name': 'ingredients_in_recipes', 'verbose_name': 'ингредиенты в рецептах'},
        ),
        migrations.AlterField(
            model_name='ingredientsinrecipes',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_in_recipes', to='recipes.ingredients'),
        ),
        migrations.AlterField(
            model_name='ingredientsinrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_in_recipes', to='recipes.recipes'),
        ),
    ]
